version: 0.2

env:
  variables:
    ECR_REPO_NAME: cth-ripo
    AWS_REGION: us-east-1
    AWS_ACCOUNT_ID: 190623961150

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_MAIN_URI}
      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:latest"

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t ${ECR_REPO_NAME}:latest .

  post_build:
    commands:
      - echo "Tagging and pushing the image to ECR..."
      - docker tag ${ECR_REPO_NAME}:latest ${ECR_IMAGE_URI}
      - docker push ${ECR_IMAGE_URI}

