version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    AWS_ACCOUNT_ID: "190623961150"
    ECR_REPO_NAME: cth-ripo

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - echo "Logging in to ECR: $ECR_MAIN_URI"
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_MAIN_URI}
      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:latest"
      - echo "ECR image URI: ${ECR_IMAGE_URI}"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t ${ECR_REPO_NAME}:latest .

  post_build:
    commands:
      - echo "Tagging and pushing image..."
      - docker tag ${ECR_REPO_NAME}:latest ${ECR_IMAGE_URI}
      - docker push ${ECR_IMAGE_URI}

